# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "maybind-sdk"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="MayBind Python SDK - Build and interact with Digital Twin services",
    author="MayBind Team",
    author_email="developers@maybind.com",
    url="https://github.com/MayBind/maybind-sdk",
    keywords=["MayBind", "Digital Twin", "AI", "SDK", "API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    MayBind Python SDK for building and interacting with Digital Twin services.
    
    This SDK provides easy access to the MayBind platform, allowing developers to:
    - Create and manage digital twin services
    - Interact with existing twin services
    - Handle authentication and API requests
    - Build applications that leverage digital twin technology
    
    Visit https://maybind.com/ for more information about the MayBind platform.
    """,  # noqa: E501
    package_data={"openapi_client": ["py.typed"]},
)